### ISSUE TITLE
'node-cloudant' failed to restage

### ISSUE THREAD

**Issue by sunnygoel8** [IBM-Bluemix/nodejs-loopback-api-cloudant#2]
Hi,

Create loopback application to connect with cloudant DB on Bluemix. Published loopback app and staged product leveraging API designer portal. when I bind Cloudant DB service with app and try to restage it, I'm getting following error. Could you please help me to resolve this ? Thanks. 

{ code: 'ESOCKETTIMEDOUT', connect: false, name: 'Error', message: 'ESOCKETTIMEDOUT', stack: 'Error: ESOCKETTIMEDOUT\n at ClientRequest. (/home/vcap/app/node_modules/request/request.js:778:19)\n at ClientRequest.g (events.js:291:16)\n at emitNone (events.js:86:13)\n at ClientRequest.emit (events.js:185:7)\n at TLSSocket.emitTimeout (_http_client.js:620:10)\n at TLSSocket.g (events.js:291:16)\n at emitNone (events.js:86:13)\n at TLSSocket.emit (events.js:185:7)\n at TLSSocket.Socket._onTimeout (net.js:339:8)\n at ontimeout (timers.js:365:14)\n at tryOnTimeout (timers.js:237:5)\n at Timer.listOnTimeout (timers.js:207:5)'

**Comment by sunnygoel8** [comment]
@rvennam , can you please help me resolve this issue? Thanks.

**Comment by sunnygoel8** [comment]
I've resolved this issue. Thanks.
